services:
  postgres:
    container_name: postgres-sql-lgi
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: LoginInfo
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - login-info
    restart: unless-stopped


volumes:
  postgres:
    driver: local

networks:
  login-info:
    driver: bridge