spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size:50MB
  logging:
    level:
      root: INFO
      com.LoginInfo.LoginInfo: DEBUG
    file:
      name: logs/application.log

springdoc:
  default-produces-media-type: application/json

